version: 2
updates:
  # Check for updates to GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'

  # Check for updates to Docker
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'docker'
    commit-message:
      prefix: 'docker'
      include: 'scope'

  # Check for updates to Docker Compose
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'docker-compose'
    commit-message:
      prefix: 'docker'
      include: 'scope'

  # Check for updates to Go modules
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'go'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    groups:
      go-modules:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
