blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/kjanat/articulate-parser/blob/master/README.md
    about: Check the README for usage instructions and examples
  - name: 💬 Discussions
    url: https://github.com/kjanat/articulate-parser/discussions
    about: Ask questions and discuss ideas with the community
